# Generated by Django 3.2.7 on 2022-04-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='INTERNATIONAL CONFERENCE ON MACHINE INTELLIGENCE & DATA SCIENCE APPLICATIONS - MIDAS', max_length=100)),
                ('about', models.TextField(max_length=5000)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
