# Generated by Django 3.2.7 on 2022-04-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_announcement_bulletpoint_internationaladvisorycommittee_nationaladvisorycommittee_organisingcommitte'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationaladvisorycommittee',
            name='committee_map',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='nationaladvisorycommittee',
            name='committee',
            field=models.ManyToManyField(blank=True, null=True, related_name='national_advisories', to='core.StakeHolder'),
        ),
    ]
