# Generated by Django 3.2.7 on 2022-04-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220427_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationaladvisorycommittee',
            name='committee_map',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='technicalprogramcommittee',
            name='committee_map',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
