# Generated by Django 3.2.7 on 2022-04-28 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220427_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internationaladvisorycommittee',
            name='committee',
        ),
        migrations.AddField(
            model_name='internationaladvisorycommittee',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='international_members', to='core.stakeholder'),
        ),
        migrations.RemoveField(
            model_name='nationaladvisorycommittee',
            name='committee',
        ),
        migrations.AddField(
            model_name='nationaladvisorycommittee',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='national_members', to='core.stakeholder'),
        ),
        migrations.RemoveField(
            model_name='technicalprogramcommittee',
            name='committee',
        ),
        migrations.AddField(
            model_name='technicalprogramcommittee',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tpc_members', to='core.stakeholder'),
        ),
    ]
