# Generated by Django 3.2.7 on 2022-04-28 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220428_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internationaladvisorycommittee',
            name='committee',
        ),
        migrations.RemoveField(
            model_name='nationaladvisorycommittee',
            name='committee',
        ),
        migrations.RemoveField(
            model_name='technicalprogramcommittee',
            name='committee',
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='international_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='international_members', to='core.internationaladvisorycommittee'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='national_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='national_members', to='core.nationaladvisorycommittee'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='tp_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tpc_members', to='core.technicalprogramcommittee'),
        ),
    ]
