# Generated by Django 3.2.7 on 2022-04-28 13:07

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220428_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.CharField(max_length=100)),
                ('home_city', models.CharField(blank=True, max_length=50)),
                ('home_state', models.CharField(blank=True, max_length=50)),
                ('home_country', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('website_url', models.URLField(default='/')),
                ('cover_image', models.FileField(upload_to='')),
                ('university_logo', models.FileField(upload_to='')),
                ('university_description', models.TextField(max_length=350)),
                ('conference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='core.conference')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackForPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=75)),
                ('pointers', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(default='', max_length=250), blank=True, null=True, size=None)),
                ('conference', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='core.conference')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org_name', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True)),
                ('logo', models.FileField(upload_to='')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_partners', to='core.conference')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentOrganisingCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.ManyToManyField(related_name='student_organisers', to='core.StakeHolder')),
                ('conference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.conference')),
            ],
        ),
        migrations.CreateModel(
            name='SteeringCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisory_chair', models.ManyToManyField(related_name='advisory_chairs', to='core.StakeHolder')),
                ('chief_patron', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chief_patron', to='core.stakeholder')),
                ('co_convener', models.ManyToManyField(related_name='co_conveners', to='core.StakeHolder')),
                ('co_patron', models.ManyToManyField(related_name='co_patrons', to='core.StakeHolder')),
                ('conference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.conference')),
                ('conference_chair', models.ManyToManyField(related_name='conference_chairs', to='core.StakeHolder')),
                ('convener', models.ManyToManyField(related_name='convener', to='core.StakeHolder')),
                ('corporate_chair', models.ManyToManyField(related_name='corporate_chairs', to='core.StakeHolder')),
                ('editorial_board', models.ManyToManyField(related_name='editorial_boards', to='core.StakeHolder')),
                ('general_chair', models.ManyToManyField(related_name='general_chairs', to='core.StakeHolder')),
                ('general_co_chair', models.ManyToManyField(related_name='general_co_chairs', to='core.StakeHolder')),
                ('honorary_chair', models.ManyToManyField(related_name='honorary_chairs', to='core.StakeHolder')),
                ('patron', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patron', to='core.stakeholder')),
                ('publicity_chair', models.ManyToManyField(related_name='publicity_chairs', to='core.StakeHolder')),
                ('special_session_chair', models.ManyToManyField(related_name='special_session_chairs', to='core.StakeHolder')),
                ('tpc_chair', models.ManyToManyField(related_name='tpc_chairs', to='core.StakeHolder')),
                ('tpc_co_chair', models.ManyToManyField(related_name='tpc_co_chairs', to='core.StakeHolder')),
                ('track_chair', models.ManyToManyField(related_name='track_chairs', to='core.StakeHolder')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('RSVP_url', models.URLField(blank=True, null=True)),
                ('scheduled_for', models.CharField(max_length=100)),
                ('session_chairs', models.TextField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('conference', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='special_sessions', to='core.conference')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('home_location', models.CharField(max_length=100)),
                ('affiliation', models.CharField(max_length=100)),
                ('avatar_image', models.FileField(upload_to='')),
                ('website', models.URLField(blank=True)),
                ('conference', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='core.conference')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleForRegularTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_date', models.DateField()),
                ('author_notification', models.DateField()),
                ('registration_deadline', models.DateField()),
                ('conference_dates', models.DateField()),
                ('conference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='early_regular_schedule', to='core.conference')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleForEarlyTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_date', models.DateField()),
                ('author_notification', models.DateField()),
                ('registration_deadline', models.DateField()),
                ('conference_dates', models.DateField()),
                ('conference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='early_track_schedule', to='core.conference')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org_name', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True)),
                ('logo', models.FileField(upload_to='')),
                ('conference', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='publication_partners', to='core.conference')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganisingCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.conference')),
                ('organising_chair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organising_chair', to='core.stakeholder')),
                ('organising_co_chair', models.ManyToManyField(related_name='co_chairs', to='core.StakeHolder')),
                ('organising_committee', models.ManyToManyField(related_name='committees', to='core.StakeHolder')),
                ('publicity_and_sponsorship_chair', models.ManyToManyField(related_name='publicity_and_sponsor_chairs', to='core.StakeHolder')),
                ('web_chair', models.ManyToManyField(related_name='web_chairs', to='core.StakeHolder')),
            ],
        ),
        migrations.CreateModel(
            name='BulletPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('avatar_image', models.FileField(upload_to='')),
                ('conference', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bulletpoints', to='core.conference')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=75)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('conference', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.conference')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
