# Generated by Django 3.2.7 on 2022-05-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_announcement_bulletpoint_organisingcommittee_publicationpartner_scheduleforearlytrack_scheduleforreg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleforearlytrack',
            name='conference_dates',
        ),
        migrations.RemoveField(
            model_name='scheduleforregulartrack',
            name='conference_dates',
        ),
        migrations.AddField(
            model_name='scheduleforearlytrack',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleforearlytrack',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleforregulartrack',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleforregulartrack',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
