# Generated by Django 3.2.7 on 2022-05-01 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220501_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steeringcommittee',
            name='advisory_chair',
        ),
        migrations.RemoveField(
            model_name='steeringcommittee',
            name='chief_patron',
        ),
        migrations.RemoveField(
            model_name='steeringcommittee',
            name='co_convener',
        ),
        migrations.RemoveField(
            model_name='steeringcommittee',
            name='co_patron',
        ),
        migrations.RemoveField(
            model_name='steeringcommittee',
            name='conference_chair',
        ),
        migrations.RemoveField(
            model_name='steeringcommittee',
            name='convener',
        ),
        migrations.RemoveField(
            model_name='steeringcommittee',
            name='corporate_chair',
        ),
        migrations.RemoveField(
            model_name='steeringcommittee',
            name='editorial_board',
        ),
        migrations.RemoveField(
            model_name='steeringcommittee',
            name='general_chair',
        ),
        migrations.RemoveField(
            model_name='steeringcommittee',
            name='general_co_chair',
        ),
        migrations.RemoveField(
            model_name='steeringcommittee',
            name='honorary_chair',
        ),
        migrations.RemoveField(
            model_name='steeringcommittee',
            name='patron',
        ),
        migrations.RemoveField(
            model_name='steeringcommittee',
            name='publicity_chair',
        ),
        migrations.RemoveField(
            model_name='steeringcommittee',
            name='special_session_chair',
        ),
        migrations.RemoveField(
            model_name='steeringcommittee',
            name='tpc_chair',
        ),
        migrations.RemoveField(
            model_name='steeringcommittee',
            name='tpc_co_chair',
        ),
        migrations.RemoveField(
            model_name='steeringcommittee',
            name='track_chair',
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=-1),
            preserve_default=-1,
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='steering_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steering_committee', to='core.steeringcommittee'),
        ),
        migrations.AddField(
            model_name='steeringcommittee',
            name='committee_map',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='steeringcommittee',
            name='conference',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='steering_committee', to='core.conference'),
        ),
    ]
