# Generated by Django 3.2.7 on 2022-05-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_stakeholder_afiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='full_name',
            field=models.CharField(max_length=500),
        ),
    ]
