# Generated by Django 3.2.7 on 2022-07-30 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_stakeholder_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='conference',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.conference'),
        ),
        migrations.AlterField(
            model_name='bulletpoint',
            name='conference',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='bulletpoints', to='core.conference'),
        ),
        migrations.AlterField(
            model_name='publicationpartner',
            name='conference',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='publication_partners', to='core.conference'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='conference',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='core.conference'),
        ),
        migrations.AlterField(
            model_name='specialsession',
            name='conference',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='special_sessions', to='core.conference'),
        ),
        migrations.AlterField(
            model_name='trackforpaper',
            name='conference',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='core.conference'),
        ),
    ]
