# Generated by Django 3.2.7 on 2022-07-30 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_fee_feetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feetype',
            name='fee_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='core.fee', verbose_name='Fee belongs to the type early, regular, etc ...'),
        ),
    ]
