# Generated by Django 3.2.7 on 2022-11-18 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_feetype_fee_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.conference'),
        ),
        migrations.AlterField(
            model_name='bulletpoint',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulletpoints', to='core.conference'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='core.conference'),
        ),
        migrations.AlterField(
            model_name='publicationpartner',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication_partners', to='core.conference'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='core.conference'),
        ),
        migrations.AlterField(
            model_name='specialsession',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_sessions', to='core.conference'),
        ),
        migrations.AlterField(
            model_name='trackforpaper',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='core.conference'),
        ),
        migrations.CreateModel(
            name='RichInformationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('name', models.CharField(max_length=25)),
                ('conference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rich_information_block', to='core.conference')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
